spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_blog?serverTimezone=UTC
    username: root
    password: aa123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.yuwenxin.blog.model  #对应实体类路径

server:
  port: 80
